sudo: required
language: generic 

services:
  - docker
before_install:
  - docker build -t rajgurus/docker-react -f Dockerfile.dev .

script:
  - docker run rajgurus/docker-react npm run test -- --coverage
